-- 1. 입원 세션 (퇴원 시 status 변경으로 접근 차단)
CREATE TABLE admissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_name_masked TEXT NOT NULL,         -- 예: 이*원 (마스킹 필수)
    room_number TEXT NOT NULL,
    access_token UUID DEFAULT gen_random_uuid() UNIQUE, -- QR 접속용 토큰
    status TEXT DEFAULT 'IN_PROGRESS',         -- IN_PROGRESS / DISCHARGED
    check_in_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    discharged_at TIMESTAMP WITH TIME ZONE,
    dob DATE,                                  -- 생년월일
    gender TEXT CHECK (gender IN ('M', 'F'))    -- 성별 (M/F)
);

-- 2. 바이탈 사인 (시계열 데이터, 그래프용)
CREATE TABLE vital_signs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    temperature NUMERIC(3, 1) NOT NULL,
    has_medication BOOLEAN DEFAULT FALSE,      -- 해열제 투약 여부 마커
    medication_type TEXT,                      -- 'A' or 'I'
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 수액 기록 (증거 남기기용)
CREATE TABLE iv_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    photo_url TEXT,                            -- 수액 조절기 촬영 사진 URL
    infusion_rate INTEGER,                     -- 주입 속도 (cc/hr)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 식단/서류 요청
CREATE TABLE meal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    request_type TEXT,                         -- GENERAL, SOFT, NPO(금식)
    pediatric_meal_type TEXT,
    guardian_meal_type TEXT,
    room_note TEXT,
    status TEXT DEFAULT 'PENDING',
    meal_date DATE DEFAULT CURRENT_DATE,       -- Added by migration 003
    meal_time VARCHAR(20) DEFAULT 'LUNCH',     -- Added by migration 003
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT check_meal_time_valid CHECK (meal_time IN ('BREAKFAST', 'LUNCH', 'DINNER'))
);

-- 5. 서류 요청
CREATE TABLE document_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    request_items TEXT[],                        -- RECEIPT, DETAIL, CERT, DIAGNOSIS, INITIAL
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. 검사 일정 (예정된 검사)
CREATE TABLE exam_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name TEXT NOT NULL,
    note TEXT DEFAULT ''
);

-- 7. Common Meal Plans (Migration 20260214)
CREATE TABLE common_meal_plans (
    date DATE PRIMARY KEY,
    breakfast TEXT,
    lunch TEXT,
    dinner TEXT,
    snack TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Patient Meal Overrides (Migration 20260214)
CREATE TABLE patient_meal_overrides (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    admission_id UUID NOT NULL REFERENCES admissions(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    meal_time VARCHAR(20) NOT NULL CHECK (meal_time IN ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('NORMAL', 'SOFT', 'FASTING', 'ALLERGY')),
    memo TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(admission_id, date, meal_time)
);

-- 9. 감사 로그 (필수 보안)
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type TEXT,                           -- NURSE, GUARDIAN
    action TEXT,                               -- VIEW, CREATE, UPDATE
    target_id TEXT,                            -- UUID or Integer ID (converted to text)
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS (Row Level Security) 설정
-- 모든 테이블에 대해 RLS 활성화
ALTER TABLE admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE vital_signs ENABLE ROW LEVEL SECURITY;
ALTER TABLE iv_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- 보안 정책 (Policies) 설정
-- 1. 백엔드 (service_role)는 모든 권한을 가짐 (기본적으로 적용됨)
-- 2. anon (클라이언트 직접 접근)은 기본적으로 모든 접근 차단
-- 3. 필요한 경우 정책 추가 (여기서는 모든 사용자의 삽입 권한을 명시적으로 허용)

-- 식단 및 서류 신청에 대한 권한 허용
-- 보호자: 조회 및 신청 가능 / 의료진(Staff): 모든 관리 권한
CREATE POLICY "Enable read for all users" ON public.meal_requests FOR SELECT USING (true);
CREATE POLICY "Allow insert for active admissions" ON public.meal_requests
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);
CREATE POLICY "Staff can manage all meal requests" ON public.meal_requests 
FOR ALL TO authenticated 
USING (auth.role() = 'authenticated') 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable read for all users" ON public.document_requests FOR SELECT USING (true);
CREATE POLICY "Allow insert for active admissions" ON public.document_requests
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);
CREATE POLICY "Staff can manage all document requests" ON public.document_requests 
FOR ALL TO authenticated 
USING (auth.role() = 'authenticated') 
WITH CHECK (auth.role() = 'authenticated');

-- 10. 입원, 바이탈, 수액 기록에 대한 읽기 권한 (대시보드 필수)
CREATE POLICY "Enable read for all users" ON public.admissions FOR SELECT USING (true);
CREATE POLICY "Enable read for all users" ON public.vital_signs FOR SELECT USING (true);
CREATE POLICY "Enable read for all users" ON public.iv_records FOR SELECT USING (true);

-- 의료진은 위 데이터에 대해 모든 관리 권한을 가짐
CREATE POLICY "Staff can manage all admissions" ON public.admissions FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Staff can manage all vital_signs" ON public.vital_signs FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Staff can manage all iv_records" ON public.iv_records FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- 11. 감사 로그 보안
CREATE POLICY "Enable insert for all users" ON public.audit_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Staff can view all audit logs" ON public.audit_logs FOR SELECT TO authenticated USING (auth.role() = 'authenticated');

-- 12. 검사 일정: 누구나 조회 가능, 관리는 의료진만
CREATE POLICY "Enable read for all users" ON public.exam_schedules FOR SELECT USING (true);
CREATE POLICY "Staff can manage all exam schedules" ON public.exam_schedules FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Common Meal Plans & Overrides Policies
ALTER TABLE common_meal_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_meal_overrides ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON common_meal_plans FOR SELECT USING (true);
CREATE POLICY "Staff can manage all common meal plans" ON common_meal_plans FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable read access for all users" ON patient_meal_overrides FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON patient_meal_overrides FOR INSERT WITH CHECK (true);
CREATE POLICY "Staff can manage all patient meal overrides" ON patient_meal_overrides FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
