-- 1. 입원 세션 (퇴원 시 status 변경으로 접근 차단)
CREATE TABLE admissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_name_masked TEXT NOT NULL,         -- 예: 이*원 (마스킹 필수)
    room_number TEXT NOT NULL,
    access_token UUID DEFAULT gen_random_uuid() UNIQUE, -- QR 접속용 토큰
    status TEXT DEFAULT 'IN_PROGRESS',         -- IN_PROGRESS / DISCHARGED
    check_in_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    discharged_at TIMESTAMP WITH TIME ZONE,
    dob DATE,                                  -- 생년월일
    gender TEXT CHECK (gender IN ('M', 'F'))    -- 성별 (M/F)
);

-- 2. 바이탈 사인 (시계열 데이터, 그래프용)
CREATE TABLE vital_signs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    temperature NUMERIC(3, 1) NOT NULL,
    has_medication BOOLEAN DEFAULT FALSE,      -- 해열제 투약 여부 마커
    medication_type TEXT,                      -- 'A' or 'I'
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 수액 기록 (증거 남기기용)
CREATE TABLE iv_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    photo_url TEXT,                            -- 수액 조절기 촬영 사진 URL
    infusion_rate INTEGER,                     -- 주입 속도 (cc/hr)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 식단/서류 요청
CREATE TABLE meal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    request_type TEXT,                         -- GENERAL, SOFT, NPO(금식)
    pediatric_meal_type TEXT,
    guardian_meal_type TEXT,
    room_note TEXT,
    status TEXT DEFAULT 'PENDING',
    meal_date DATE DEFAULT CURRENT_DATE,       -- Added by migration 003
    meal_time VARCHAR(20) DEFAULT 'LUNCH',     -- Added by migration 003
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT check_meal_time_valid CHECK (meal_time IN ('BREAKFAST', 'LUNCH', 'DINNER'))
);

-- 5. 서류 요청
CREATE TABLE document_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    request_items TEXT[],                        -- RECEIPT, DETAIL, CERT, DIAGNOSIS, INITIAL
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. 검사 일정 (예정된 검사)
CREATE TABLE exam_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name TEXT NOT NULL,
    note TEXT DEFAULT ''
);

-- 7. Common Meal Plans (Migration 20260214)
CREATE TABLE common_meal_plans (
    date DATE PRIMARY KEY,
    breakfast TEXT,
    lunch TEXT,
    dinner TEXT,
    snack TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Patient Meal Overrides (Migration 20260214)
CREATE TABLE patient_meal_overrides (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    admission_id UUID NOT NULL REFERENCES admissions(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    meal_time VARCHAR(20) NOT NULL CHECK (meal_time IN ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('NORMAL', 'SOFT', 'FASTING', 'ALLERGY')),
    memo TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(admission_id, date, meal_time)
);

-- 9. 감사 로그 (필수 보안)
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type TEXT,                           -- NURSE, GUARDIAN
    action TEXT,                               -- VIEW, CREATE, UPDATE
    target_id TEXT,                            -- UUID or Integer ID (converted to text)
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS (Row Level Security) 설정
-- 모든 테이블에 대해 RLS 활성화
ALTER TABLE admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE vital_signs ENABLE ROW LEVEL SECURITY;
ALTER TABLE iv_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- 보안 정책 (Policies) 설정
-- 1. 백엔드 (service_role)는 모든 권한을 가짐 (기본적으로 적용됨)
-- 2. anon (클라이언트 직접 접근)은 기본적으로 모든 접근 차단
-- 3. 필요한 경우 정책 추가 (여기서는 모든 사용자의 삽입 권한을 명시적으로 허용)

-- 식단 및 서류 신청에 대한 권한 허용
-- 보호자: 활성 세션인 경우에만 조회 및 신청 가능 / 의료진(Staff): 모든 관리 권한
CREATE POLICY "Enable read for active sessions" ON public.meal_requests 
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);
CREATE POLICY "Allow insert for active admissions" ON public.meal_requests
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);
CREATE POLICY "Staff can manage all meal requests" ON public.meal_requests 
FOR ALL TO authenticated 
USING (auth.role() = 'authenticated') 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable read for active sessions" ON public.document_requests 
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);
CREATE POLICY "Allow insert for active admissions" ON public.document_requests
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);
CREATE POLICY "Staff can manage all document requests" ON public.document_requests 
FOR ALL TO authenticated 
USING (auth.role() = 'authenticated') 
WITH CHECK (auth.role() = 'authenticated');

-- 10. 입원, 바이탈, 수액 기록에 대한 읽기 권한 (대시보드 필수)
-- 보호자: 현재 입원 중인 데이터만 조회 가능
CREATE POLICY "Enable read for active admissions" ON public.admissions 
FOR SELECT USING (status = 'IN_PROGRESS' OR status = 'OBSERVATION');

CREATE POLICY "Enable read for active sessions" ON public.vital_signs 
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);

CREATE POLICY "Enable read for active sessions" ON public.iv_records 
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);

-- 의료진은 위 데이터에 대해 모든 관리 권한을 가짐
CREATE POLICY "Staff can manage all admissions" ON public.admissions FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Staff can manage all vital_signs" ON public.vital_signs FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Staff can manage all iv_records" ON public.iv_records FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- 11. 감사 로그 보안
-- 누구나 로그를 남길 수는 있지만, 액터 타입이 정의된 형식(NURSE, GUARDIAN)인 경우만 허용하여 무분별한 삽입 방지
CREATE POLICY "Enable insert for all users" ON public.audit_logs 
FOR INSERT WITH CHECK (actor_type IN ('NURSE', 'GUARDIAN'));
CREATE POLICY "Staff can view all audit logs" ON public.audit_logs FOR SELECT TO authenticated USING (auth.role() = 'authenticated');

-- 12. 검사 일정: 누구나 조회 가능, 관리는 의료진만
CREATE POLICY "Enable read for all users" ON public.exam_schedules FOR SELECT USING (true);
CREATE POLICY "Staff can manage all exam schedules" ON public.exam_schedules FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Common Meal Plans & Overrides Policies
ALTER TABLE common_meal_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_meal_overrides ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON common_meal_plans FOR SELECT USING (true);
CREATE POLICY "Staff can manage all common meal plans" ON common_meal_plans FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable read access for all users" ON patient_meal_overrides FOR SELECT USING (true);
CREATE POLICY "Allow insert for active admissions" ON patient_meal_overrides
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM admissions 
    WHERE admissions.id = admission_id 
    AND admissions.status = 'IN_PROGRESS'
  )
);
CREATE POLICY "Staff can manage all patient meal overrides" ON patient_meal_overrides FOR ALL TO authenticated USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
-- // ... existing policies ....

-- 13. 핵심 트랜잭션 함수 (RPC)
-- SECURITY DEFINER를 사용하여 백엔드(anon)에서도 RLS를 우회하여 입원 처리가 가능하도록 함

-- A. 입원 등록
CREATE OR REPLACE FUNCTION create_admission_transaction(
    p_patient_name_masked TEXT,
    p_room_number TEXT,
    p_dob DATE,
    p_gender TEXT,
    p_check_in_at TIMESTAMPTZ,
    p_actor_type TEXT,
    p_ip_address TEXT
) RETURNS JSON AS $$
DECLARE
    v_admission_id UUID;
    v_token UUID;
BEGIN
    INSERT INTO admissions (
        patient_name_masked, 
        room_number, 
        status, 
        dob, 
        gender, 
        check_in_at
    ) VALUES (
        p_patient_name_masked,
        p_room_number,
        'IN_PROGRESS',
        p_dob,
        p_gender,
        COALESCE(p_check_in_at, NOW())
    ) RETURNING id, access_token INTO v_admission_id, v_token;

    INSERT INTO audit_logs (actor_type, action, target_id, ip_address)
    VALUES (p_actor_type, 'CREATE', v_admission_id, p_ip_address);

    RETURN json_build_object('id', v_admission_id, 'access_token', v_token);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- B. 전실 (방 이동)
CREATE OR REPLACE FUNCTION transfer_patient_transaction(
    p_admission_id UUID,
    p_target_room TEXT,
    p_actor_type TEXT,
    p_ip_address TEXT
) RETURNS JSON AS $$
DECLARE
    v_old_room TEXT;
    v_token UUID;
BEGIN
    IF EXISTS (SELECT 1 FROM admissions WHERE room_number = p_target_room AND status = 'IN_PROGRESS') THEN
        RAISE EXCEPTION 'Room % is occupied', p_target_room;
    END IF;

    SELECT room_number, access_token INTO v_old_room, v_token
    FROM admissions WHERE id = p_admission_id AND status = 'IN_PROGRESS' FOR UPDATE;

    IF NOT FOUND THEN RAISE EXCEPTION 'Active admission not found'; END IF;

    UPDATE admissions SET room_number = p_target_room, discharged_at = NULL WHERE id = p_admission_id;

    INSERT INTO audit_logs (actor_type, action, target_id, ip_address)
    VALUES (p_actor_type, 'TRANSFER', p_admission_id, p_ip_address);

    RETURN json_build_object('admission_id', p_admission_id, 'old_room', v_old_room, 'new_room', p_target_room, 'token', v_token);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- C. 퇴원 처리
CREATE OR REPLACE FUNCTION discharge_patient_transaction(
    p_admission_id UUID,
    p_actor_type TEXT,
    p_ip_address TEXT
) RETURNS JSON AS $$
DECLARE
    v_room TEXT;
    v_token UUID;
BEGIN
    UPDATE admissions
    SET status = 'DISCHARGED', discharged_at = NOW()
    WHERE id = p_admission_id AND status = 'IN_PROGRESS'
    RETURNING room_number, access_token INTO v_room, v_token;

    IF NOT FOUND THEN RAISE EXCEPTION 'Active admission not found'; END IF;

    INSERT INTO audit_logs (actor_type, action, target_id, ip_address)
    VALUES (p_actor_type, 'DISCHARGE', p_admission_id, p_ip_address);

    RETURN json_build_object('admission_id', p_admission_id, 'room', v_room, 'token', v_token);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
