-- 1. 입원 세션 (퇴원 시 status 변경으로 접근 차단)
CREATE TABLE admissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_name_masked TEXT NOT NULL,         -- 예: 이*원 (마스킹 필수)
    room_number INTEGER NOT NULL,
    access_token UUID DEFAULT gen_random_uuid() UNIQUE, -- QR 접속용 토큰
    status TEXT DEFAULT 'IN_PROGRESS',         -- IN_PROGRESS / DISCHARGED
    check_in_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    discharged_at TIMESTAMP WITH TIME ZONE
);

-- 2. 바이탈 사인 (시계열 데이터, 그래프용)
CREATE TABLE vital_signs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    temperature NUMERIC(3, 1) NOT NULL,
    has_medication BOOLEAN DEFAULT FALSE,      -- 해열제 투약 여부 마커
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 수액 기록 (증거 남기기용)
CREATE TABLE iv_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    photo_url TEXT,                            -- 수액 조절기 촬영 사진 URL
    infusion_rate INTEGER,                     -- 주입 속도 (cc/hr)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 식단/서류 요청
CREATE TABLE meal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    request_type TEXT,                         -- GENERAL, SOFT, NPO(금식)
    status TEXT DEFAULT 'PENDING'
);

-- 5. 서류 요청
CREATE TABLE document_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES admissions(id),
    request_items TEXT[],                        -- RECEIPT, DETAIL, CERT, DIAGNOSIS, INITIAL
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. 감사 로그 (필수 보안)
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type TEXT,                           -- NURSE, GUARDIAN
    action TEXT,                               -- VIEW, CREATE, UPDATE
    target_id UUID,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS (Row Level Security) 설정
-- 모든 테이블에 대해 RLS 활성화
ALTER TABLE admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE vital_signs ENABLE ROW LEVEL SECURITY;
ALTER TABLE iv_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- 보안 정책 (Policies) 설정
-- 1. 백엔드 (service_role)는 모든 권한을 가짐 (기본적으로 적용됨)
-- 2. anon (클라이언트 직접 접근)은 기본적으로 모든 접근 차단
-- 3. 필요한 경우 정책 추가 (여기서는 모든 사용자의 삽입 권한을 명시적으로 허용)

-- 식단 및 서류 신청에 대한 삽입 권한 허용
CREATE POLICY "Enable insert for all users" ON public.meal_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for all users" ON public.document_requests FOR INSERT WITH CHECK (true);

-- 감사 로그에 대한 삽입 권한 허용한
CREATE POLICY "Enable insert for all users" ON public.audit_logs FOR INSERT WITH CHECK (true);
