# Shared-DocsConstants.ps1
# C-3 SSOT: Invoke-DocsRefactor.ps1 및 Verify-DocsLinks.ps1이 공유하는 아카이브 파일명 목록.
# 이 파일을 Dot-sourcing하여 목록을 단일 출처에서 관리한다.
# 인코딩: UTF-8 with BOM (PowerShell 스크립트 표준)

$script:ARCHIVED_DOC_NAMES = @(
    "DIAGNOSIS_PATIENT_DETAIL_MODAL_LOGIC.md",
    "DIAGNOSIS_DASHBOARD_PAGE_LOGIC.md",
    "DIAGNOSIS_USE_DASHBOARD_STATS_LOGIC.md",
    "DIAGNOSIS_MEAL_MODULES_LOGIC.md",
    "DIAGNOSIS_USEVITALS_LOGIC.md",
    "PROMPT_COMPLETED_DOCS_NOT_SHOWING.md",
    "PROMPT_STATION_INITIAL_LOAD_EMPTY.md",
    "PROMPT_OTHER_LLM_STATION_GRID_EMPTY.md",
    "PROMPT_OTHER_LLM_STATION_GRID_DB_SQL_VERIFICATION.md",
    "PROMPT_ECO_BAT_1_CLOSES_TERMINAL.md",
    "PROMPT_WT_LAYOUT_INVESTIGATION.md",
    "PROMPT_STATION_DEV_BUTTONS_MISSING.md",
    "PROMPT_MEAL_SYNC_SUBMODAL_STALE.md",
    "PROMPT_DEPENDENCY_ISSUES.md",
    "PROMPT_REFACTOR_LOGIC_ONLY_PROTOCOL.md",
    "PROMPT_REFACTOR_AREAS_AND_CHECKLIST.md",
    "PROMPT_LOGIC_ONLY_REFACTOR_BATCH.md"
)
